### ISSUE TITLE
No display of data in Colab Notebook

### ISSUE THREAD

**Issue by Romain-Laine** [imjoy-team/imjoy-interactive-segmentation#25]
Hi Wei, 
Thanks again for the amazing tool! I'd like to train a CellPose segmentation model using the interactive tool in Google Colab, so I am trying to get it to work on the example dataset first. Following the steps of the video, I do not manage to get images to be displayed in Kaibu. See below. Any ideas what I may be doing wrong?

I have simply done the following:
- upload the tutorial.jpynb notebook to Colab
- run the install
- restart the session 
- re-run the install cell
- run the cell starting up the interactive tool
- play around trying to get images

<img width="1440" alt="Screenshot 2021-03-01 at 12 44 34" src="https://user-images.githubusercontent.com/21193399/109498977-2cc43b80-7a8c-11eb-8f54-73957f8144c0.png">

Thanks a lot!

Romain

**Comment by oeway** [comment]
Hey @Romain-Laine Thanks for testing this!

I see, I cannot see an immediate issue, from the screen, it appears you have got the file list and you are using Safari?

We haven't test it in Safari, could you try it in Chrome or Firefox? Also you don't need to restart the runtime (ignore the warning would be fine). So basically:
1. upload the notebook
2. open it in Chrome or firefox (latest version)
3. change the runtime type to GPU
4. install and run

**Comment by Romain-Laine** [comment]
Works a dream in Chrome!
I feel embarrassed to have fallen for that silly mistake, especially since the paper does mention Chrome and Firefox explicitly.
Thanks a lot, Wei.

Romain

**Comment by oeway** [comment]
Great! @Romain-Laine No worries. I now recall why it doesn't work, it's related to the safari bug I reported a few days ago: https://github.com/Kitware/itk-vtk-viewer/issues/386 Which should be fixed soon.
